services:
  logger-server:
    image: nntile_logger_server
    build:
      dockerfile: Dockerfile
      context: logger
    environment:
      - SERVER_PORT=5001
      - LOG_DIR=/workspace/logs
      - CLEAR_LOGS=1
      - SPLIT_HOURS=24
      - TENSORBOARD_PORT=6006
    ports:
      - ${NNTILE_LOGGER_PORT:-5001}:5001
      - ${NNTILE_TB_PORT}:6006
      - ${NNTILE_TB_TLS_PORT:-6443}:6443
    cpus: 1

  jupyter-lab:
    image: nntile_jupyter_lab
    build:
      dockerfile: notebooks/Dockerfile
      context: ./
      args:
        MAKE_JOBS: 8
    ports:
      - ${NNTILE_LAB_PORT}:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
